name: ci-cd

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-cd.yaml
      - src/**
      - tests/**
  release:
    types:
      - published

jobs:
  check-quality:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/alvarobartt/wandbfsspec:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: quality
        run: poetry run make quality

  run-tests:
    needs: check-quality

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/alvarobartt/wandbfsspec:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-package
        run: poetry install

      - name: tests
        run: poetry run make tests
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

  publish-package:
    needs: run-tests
    if: github.event_name == 'release'

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/alvarobartt/wandbfsspec:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: config-pypi
      run: poetry config pypi-token.pypi $WANDBFSSPEC_PYPI_TOKEN
      env:
        WANDBFSSPEC_PYPI_TOKEN: ${{ secrets.WANDBFSSPEC_PYPI_TOKEN }}

    - name: publish-package
      run: poetry publish --build